#pragma once

#define MAX_GAMEROOM_USERCOUNT				16

#define LENGTH_STARTDATE					20
#define LENGTH_PDATE						4



#ifdef SF_CONTEST_SERVER
#define NUM_PERSONGAME_VICTORYCONDITION		30			// 개인전의 기본 킬 수
#define NUM_TEAMGAME_VICTORYCONDITION		7			// 팀전의 기본 승수(대회)
#define NUM_EXERCISEGAME_VICTORYCONDITION	0			// 연습모드 승수
#define NUM_CLANGAME_VICTORYCONDITION		5			// 클랜전의 승수
#define NUM_CONTESTGAME_VICTORYCONDITION	5			// 대회 모드 승수
#define NUM_CLAN_LADDERGAME_VICTORYCONDITION             5           //클랜래더 승수
#define NUM_PERSONAL_LADDERGAME_VICTORYCONDITION         10          //개인래더 승수
#define NUM_CTC_VICTORYCONDITION            5           
#define NUM_TEAM_DEATH_VICTORYCONDITION     6           // 팀데스 승수
#define NUM_OCCUPY_VICTORYCONDITION			5			// 점령전 승수
#define NUM_SNIPER_VICTORYCONDITION			8
#define NUM_CTCRENEWAL_VICTORYCONDITION     7           // 팀데스 승수
#define	NUM_ZOMBIEMODE_VICTORYCONDITION		5
#define NUM_ADGAME_VICTORYCONDITION			2
#define NUM_PIRATE_VICTORYCONDITION			5			
#define	NUM_ZOMBIEMODE2_VICTORYCONDITION	4
#define	NUM_LEAGUEMODE_VICTORYCONDITION		5
#else
#define NUM_PERSONGAME_VICTORYCONDITION					30			// 개인전의 기본 킬 수
#define NUM_TEAMGAME_VICTORYCONDITION					8			// 팀전의 기본 승수
#define NUM_EXERCISEGAME_VICTORYCONDITION				0			// 연습모드 승수
#define NUM_CLANGAME_VICTORYCONDITION					5			// 클랜전의 승수
#define NUM_CONTESTGAME_VICTORYCONDITION				5			// 대회 모드 승수
#define NUM_CLAN_LADDERGAME_VICTORYCONDITION            5           // 클랜래더 승수
#define NUM_PERSONAL_LADDERGAME_VICTORYCONDITION        10          // 개인래더 승수
#define NUM_CTC_VICTORYCONDITION						5           
#define NUM_TEAM_DEATH_VICTORYCONDITION					1           // 팀데스 승수
#define NUM_OCCUPY_VICTORYCONDITION						5			// 점령전 승수
#define NUM_SNIPER_VICTORYCONDITION						8
#define NUM_CTCRENEWAL_VICTORYCONDITION					2           // 팀데스 승수
#define	NUM_ZOMBIEMODE_VICTORYCONDITION					5
#define NUM_ADGAME_VICTORYCONDITION						2
#define NUM_PIRATE_VICTORYCONDITION						0			
#define	NUM_ZOMBIEMODE2_VICTORYCONDITION				4
#define	NUM_LEAGUEMODE_VICTORYCONDITION					5
#endif

#define ERR_BEUNDERSTAFFED					0			// 시작할 인원이 부족
#define ERR_NOTALLREADY						1			// 모두 Ready 상태가 아님
#define ERR_DONTEXIST_REALIP				2			// Real IP가 없음
#define ERR_NOT_TEAMGAMECONDITION			3			// 양쪽의 인원이 맞지 않음
#define ERR_NOT_CLANGAMECONDITION			4			// 클랜이 2개 초과거나 양쪽에 서로 다른 클랜이 있지 않음

#define TEAM_RED							0			// Red 팀의 번호
#define TEAM_BLUE							1			// Blue 팀의 번호
#define TEAM_ALL							2			// 구분없음

#define NUM_MISSION_MIN						0		
#define NUM_MISSION_MAX						99

enum JudgeGameCloseState
{
	CHECK_GAMEROUND_STATE = 0,
	CHECK_KILLCOUNT_STATE = 1,
	CHECK_USERCOUNT_STATE = 2,
};

enum GAME_VICTORYCONDITION_TYPE
{
	GAME_VICTORYTYPE_ROUND,
	GAME_VICTORYTYPE_TIME,
	GAME_VICTORYTYPE_POINT,
};

enum GameRoom_Status
{
	WAITROOM_STATUS = 0,			
	LOADINGROOM_STATUS = 1,				
	GAMINGROOM_STATUS = 2, 
	MATCHINGROOM_STATUS = 3,
};




